"""index

Revision ID: 85371096002f
Revises: b1e8e7dd2c0e
Create Date: 2025-06-19 13:48:47.956218

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85371096002f"
down_revision: str | None = "b1e8e7dd2c0e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("file_storage_sessionId_idx", "file_storage", ["sessionId"], unique=False)
    op.create_index("chat_messages_sessionId_idx", "chat_messages", ["sessionId"], unique=False)
    op.create_index(
        "chat_messages_sessionId_createdDate_idx",
        "chat_messages",
        ["sessionId", "createdDate"],
        unique=False,
    )
    op.create_index("chat_messages_createdDate_idx", "chat_messages", ["createdDate"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("chat_messages_createdDate_idx", table_name="chat_messages")
    op.drop_index("chat_messages_sessionId_createdDate_idx", table_name="chat_messages")
    op.drop_index("chat_messages_sessionId_idx", table_name="chat_messages")
    op.drop_index("file_storage_sessionId_idx", table_name="file_storage")
    # ### end Alembic commands ###
