"""init

Revision ID: b1e8e7dd2c0e
Revises:
Create Date: 2025-06-19 13:30:06.777456

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1e8e7dd2c0e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_messages",
        sa.Column("chatId", sa.String(), nullable=False),
        sa.Column("sessionId", sa.String(), nullable=False),
        sa.Column("role", sa.Enum("HUMAN", "AI", name="chatrole"), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), nullable=True),
        sa.Column("agentReasoning", sa.Text(), nullable=True),
        sa.Column("usedTools", sa.Text(), nullable=True),
        sa.Column("sourceDocuments", sa.Text(), nullable=True),
        sa.Column("chatType", sa.Enum("EXTERNAL", "INTERNAL", name="chattype"), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("createdDate", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("chatId", "role"),
    )
    op.create_table(
        "file_storage",
        sa.Column("sessionId", sa.String(), nullable=False),
        sa.Column("checkSum", sa.String(), nullable=False),
        sa.Column("fileName", sa.String(), nullable=False),
        sa.Column("fileType", sa.String(), nullable=False),
        sa.Column("blob", sa.LargeBinary(), nullable=False),
        sa.Column("createdDate", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("sessionId", "checkSum"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_storage")
    op.drop_table("chat_messages")
    # ### end Alembic commands ###
